### ISSUE TITLE
Error reading fine-tuned models

### ISSUE THREAD

**Issue by dmitrytoda** [neulab/awesome-align#2]
I am trying to load one of your multilingually fine-tuned models to use it on a new language pair.
I downloaded both with and without `--train_co` options to my google drive and try to launch them from colab with

```
%%bash
DATA_FILE=/content/drive/MyDrive/WordAlign/gold1/ruzh.char.src-tgt
MODEL_NAME_OR_PATH=/content/drive/MyDrive/WordAlign/models/aa_fine_model
OUTPUT_FILE=/content/drive/MyDrive/WordAlign/AA_output/gold1.char.aa_fine.phar

CUDA_VISIBLE_DEVICES=0 python /content/drive/MyDrive/WordAlign/awesome/run_align.py \
    --output_file=$OUTPUT_FILE \
    --model_name_or_path=$MODEL_NAME_OR_PATH \
    --data_file=$DATA_FILE \
    --extraction 'softmax' \
    --batch_size 32 \
```
I get the following error (this is for w/o `--train_co`; the other one produces similar output except byte and position are different in the last line):

> 2021-02-06 16:23:39.143584: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
>   File "/content/drive/MyDrive/WordAlign/awesome/run_align.py", line 194, in <module>
>     main()
>   File "/content/drive/MyDrive/WordAlign/awesome/run_align.py", line 167, in main
>     config = config_class.from_pretrained(args.model_name_or_path, cache_dir=args.cache_dir)
>   File "/content/drive/MyDrive/WordAlign/awesome/configuration_utils.py", line 175, in from_pretrained
>     config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "/content/drive/MyDrive/WordAlign/awesome/configuration_utils.py", line 227, in get_config_dict
>     config_dict = cls._dict_from_json_file(resolved_config_file)
>   File "/content/drive/MyDrive/WordAlign/awesome/configuration_utils.py", line 313, in _dict_from_json_file
>     text = reader.read()
>   File "/usr/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 52: invalid start byte

When I try to use base BERT without fine-tuning with `MODEL_NAME_OR_PATH=bert-base-multilingual-case`, everything works as expected.

**Comment by zdou0830** [comment]
Hi, it seems that this is related to https://github.com/neulab/awesome-align/issues/1. Just to confirm, is `/content/drive/MyDrive/WordAlign/models/aa_fine_model` the model directory that contains `pytorch_model.bin`, `config.json`, `special_tokens_map.json`, `tokenizer_config.json`, `vocab.txt`?

**Comment by dmitrytoda** [comment]
My bad, I was downloading with wget directly to my own google drive and did not realize that was a zip with  stuff inside, not just one big model file.
