### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by leileilin** [neulab/awesome-align#22]
问一下中英的这个已经微调好的模型可以在英中方向上做单词对齐吗？还是需要重新无监督微调英中方向的？

**Comment by zdou0830** [comment]
你好，直接用multilingual BERT做对齐就能取得蛮好的效果。如果把multilingual BERT在你的数据上微调一下应该会更好。

**Comment by leileilin** [comment]
> 你好，直接用multilingual BERT做对齐就能取得蛮好的效果。如果把multilingual BERT在你的数据上微调一下应该会更好。

非常感谢你的回答。我的本意是想只用一个模型同时可以做中英和英中方向的单词对齐，不知道先用中英方向的数据微调，而后用英中方向的数据微调，这个做法可不可行？还是原来你这边中英方向已经微调好的模型就可以做双向的单词对齐预测？

**Comment by zdou0830** [comment]
我们的模型是和方向无关的，中英和英中得到的结果一样。

**Comment by leileilin** [comment]
> 我们的模型是和方向无关的，中英和英中得到的结果一样。

好的，我明白了，非常感谢你的解答。
