### ISSUE TITLE
Can I use awesome-align for monosyllabic language

### ISSUE THREAD

**Issue by quocthang0507** [neulab/awesome-align#25]
Can I use awesome-align for monosyllabic language (e.g. Vietnamese).
For example:
Instead of:
"sinh"==="student"
"viên"==="student"
Want to:
"sinh viên"==="student"
Thanks for your project.

**Comment by zdou0830** [comment]
Hi, thanks! right now awesome-align separates a sentence into words based on white space and only supports outputting word-level alignments.

**Comment by quocthang0507** [comment]
I found that your code used `src.strip().split()` and `tgt.strip().split()`.
Therefore, I chose another word segmenter that supports Vietnamese and replaced it. Hope it works perfectly. 😂
