### ISSUE TITLE
setting output prob file and output word file

### ISSUE THREAD

**Issue by pskadasi** [neulab/awesome-align#26]
how do i set output prob file and output word file to get the alignemnents as said in this snap ? 
<srcword><sep><tgtword. Can you give me an example. There is no option for this.
![image](https://user-images.githubusercontent.com/48944276/130250467-7fd6aedb-8f48-4ef1-9104-c9a83deeacfd.png)
>

**Comment by zdou0830** [comment]
Hi, you can see the options here https://github.com/neulab/awesome-align/blob/master/awesome_align/run_align.py#L222-L227. 

An example:
```
DATA_FILE=/path/to/data/file
MODEL_NAME_OR_PATH=bert-base-multilingual-cased
OUTPUT_FILE=/path/to/output/file
OUTPUT_PROB_FILE=/path/to/output/prob/file
OUTPUT_WORD_FILE=/path/to/output/word/file

CUDA_VISIBLE_DEVICES=0 awesome-align \
    --output_file=$OUTPUT_FILE \
    --model_name_or_path=$MODEL_NAME_OR_PATH \
    --data_file=$DATA_FILE \
    --extraction 'softmax' \
    --output_prob_file $OUTPUT_PROB_FILE \
    --output_word_file $OUTPUT_WORD_FILE \
    --batch_size 32
```

**Comment by pskadasi** [comment]
thanks for the very quick response. it worked :)
