### ISSUE TITLE
De-En dataset is missing

### ISSUE THREAD

**Issue by ruoyuxyz** [neulab/awesome-align#27]
Hello,

I could not find the De-En dataset on the provided link. It is not on the examples folder either. Where can I find this dataset? 

Thank you

**Comment by zdou0830** [comment]
Hi, you can follow the steps in this [repo](https://github.com/lilt/alignment-scripts). In particular, you'll need to download [test data for German-English](https://www-i6.informatik.rwth-aachen.de/goldAlignment/) and move it into the folder `test`.
