### ISSUE TITLE
Training with gold alignment

### ISSUE THREAD

**Issue by ruoyuxyz** [neulab/awesome-align#31]
Hi, 

Thanks again for such a great alignment tool!

I was trying to train the model with gold alignments, but I keep getting the following error message:

**awesome-train: error: unrecognized arguments: --train_gold_file=examples/enfr.gold**

I used the Supervised Settings example command from README. My TRAIN_FILE is formated as tokenized src ||| tgt, and the TRAIN_GOLD_FILE is gold alignment pairs (eg: enfr.gold). 

Am I missing anything? 

Thanks!

**Comment by zdou0830** [comment]
Hello, it's possible that you are using an old version. Could you check if `pip install awesome_align==0.1.6` or `git clone` the current repo and then `python setup.py install` would solve the issue? Thanks!

**Comment by ruoyuxyz** [comment]
> Hello, it's possible that you are using an old version. Could you check if `pip install awesome_align==0.1.6` or `git clone` the current repo and then `python setup.py install` would solve the issue? Thanks!

It works! Thanks a lot!
