### ISSUE TITLE
Can I evaluate separately?

### ISSUE THREAD

**Issue by ruoyuxyz** [neulab/awesome-align#34]
Hi, 

I had _**AttributeError: 'DataParallel' object has no attribute 'get_aligned_word'**_ error while using multiple GPUs to fine-tune the model. I noticed that this error occurs at the beginning of the evaluation, and even the evaluation failed, there was still a trained model created. My question is that can I evaluate this newly created model separately? 

I was thinking something like below. Am I missing anything?
_./awesome-train   --output_dir=path/to/output   --model_name_or_path=trained-model-with-failed-evaluation   --do_eval    --eval_data_file=$EVAL_FILE_ 

Thanks!

**Comment by zdou0830** [comment]
Hello, you can just remove the `do_eval` flag. Also, it is recommended to use DistributedDataParallel instead of DataParallel as using DataParallel can actually make the training slower with multiple GPUs.
