### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by bitPogo** [neulab/awesome-align#5]
Hey,

First of all - thanks for the awesome work with awesome aligner. I am currently working on a small annotation projection project, which makes use of awesome-align. However, it would great if you scope at last the auxiliary files (like `modeling.py`) into a dedicated folder such as `awesomealign`. Thanks!

**Comment by bitPogo** [comment]
By the way...I made already a [fork](https://github.com/bitPogo/awesome-align/tree/pontifex) which contains the necessary changes. Probably the setup.py needs some polishing, but I could make a PR out of it, if you like.

**Comment by zdou0830** [comment]
sure, contributions are welcome :)

**Comment by bitPogo** [comment]
Sure, please have look before on the `setup.py` - if you want to leave it out or not. I need to make sure, that my dependencies do not break.

**Comment by zdou0830** [comment]
Thanks! That looks good (except maybe I'd name it `awesome_align` instead of `awesomealign`) and I'll take a close look at it once you make the PR.
