### ISSUE TITLE
pip packaging?

### ISSUE THREAD

**Issue by neubig** [neulab/awesome-align#8]
With the new `setup.py` (https://github.com/neulab/awesome-align/pull/7), it might be nice to also have awesome-align be installable through pip as well?

**Comment by bitPogo** [comment]
You can actually can via: 
``` bash 
pip install -e git+https://github.com/neulab/awesome-align#egg=awesome_align
```

**Comment by neubig** [comment]
Cool, thanks. I guess I actually meant something like "pypi packaging" so you don't need to do it directly with the URL.

**Comment by zdou0830** [comment]
Uploaded awesome-align to pypi (https://pypi.org/project/awesome-align/).

**Comment by neubig** [comment]
@zdou0830 Awesome, thanks! Maybe also update the README?
